### ISSUE TITLE
Announcement

### ISSUE THREAD

**Issue by srid** [ekala-project/eka#14]
Plan for our announcement.

## Design & Website

Domain: `ekala.org`

- Landing page
- Conceptual split
	- Eka introduction
	- Jon's plan for nixpkgs fork
- Community: 
  - [x] Discord
  - [ ] Discourse
  - [ ] X
  - [ ] subreddit https://old.reddit.com/r/ekala/
  - [ ] Week letter. "This week in Ekala"
  
- Email
  - ekala@gmail.com or Google workspaces. If not later, you can setup redirect `foo@ekala.com` -> `ekala@gmail.com`

## Timing

- SC election results announced [Oct 23rd](https://github.com/NixOS/SC-election-2024#timeline), Wednesday.
  - [ ] When do we announce?

## Make announcements

- [ ] reddit
- [ ] NixOS Discourse (important!)

**Comment by nrdxp** [comment]
The repo is now public and so is Ekala, so closing
